-- Even Fibonacci numbers
-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
--   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

function fib_with_upper(upper)
  result=2
  start1=1
  start2=2
  start3=0
  while start3<upper do
    start3=start1+start2
    start1=start2
    start2=start3
    if start3%2==0 then
      result=start3+result
    end
  end
  print(result)
end

fib_with_upper(4000000)
